jobs:
- job: CodeBuild
  pool:
    name: 'DAS - Continuous Integration Agents'
    workspace:
      clean: all
  variables:
  - group: BUILD Management Resources
  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks

  - task: DotNetCoreCLI@2
    displayName: Publish Employer Accounts Api
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.EmployerAccounts.Api/SFA.DAS.EmployerAccounts.Api.csproj
      arguments: --configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: DotNetCoreCLI@2
    displayName: Publish Employer Accounts Web
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.EmployerAccounts.Web/SFA.DAS.EmployerAccounts.Web.csproj
      arguments: --configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: DotNetCoreCLI@2
    displayName: Publish Employer Accounts WebJobs
    inputs:
      command: publish
      publishWebProjects: false
      projects: src/SFA.DAS.EmployerAccounts.Webjobs.Host/SFA.DAS.EmployerAccounts.Webjobs.Host.csproj
      arguments: --configuration release --output $(build.artifactstagingdirectory)/publish --no-restore --no-build

  - task: CopyFiles@2
    displayName: Copy Files to $(build.artifactstagingdirectory)/publish
    inputs:
      Contents: |
        azure/**
        src/**/bin/**/*.dacpac
      TargetFolder: $(build.artifactstagingdirectory)/publish

  - task: PublishPipelineArtifact@1
    displayName: Publish Build Artifact
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: ${{ parameters.SolutionBaseName }}
